### PR TITLE
fix: update python version to 3.11

### PR DESCRIPTION
**Pull request by chenlizhong**
To improve performance of insights-engine, update the python version from 3.6.8 to 3.11

### CODE REVIEW

**Comment by chenlizhong** [comment]
@SteveHNH Could you please review this?

**Comment by chenlizhong** [comment]
@dkuc @SteveHNH  WIll QE team help to verify this first?

**Comment by dkuc** [comment]
I don't think QE has ever been involved at the base layer.  The services that use this will just need to be tested during their next deployment that pulls this in.

**Comment by chenlizhong** [comment]
@dkuc  so it is safe to merge. Right?   The production environment do not use the base image after the MR is merged immediately。 The newly update will be used in next deployment. 
Under this situation, you can merge this.  I have tested in my local.  During next deployment, more testings from QE scripts will be run.

**Comment by SteveHNH** [comment]
@chenlizhong I'll go ahead and merge. It will go to stage first so we should see any problems, if any, arise there first.

**Pull request merged**
